version: "3.9"

services:
#  server:
#    image: charge-images/chargeproxy:1.0
#    networks:
#      - global
#    ports:
#      - "8081:8080"
#    environment:
#      ASAAS_URL: ${ASAAS_URL}
#      ASAAS_TOKEN: ${ASAAS_TOKEN}
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - global
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure

networks:
  global:
    driver: overlay
