version: "3.9"

services:
  server:
    image: charge-images/chargeproxy:1.0
    networks:
      - global
    ports:
      - "8081:8080"
    environment:
      ASAAS_URL: ${ASAAS_URL}
      ASAAS_TOKEN: ${ASAAS_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  global:
    driver: overlay
